service:
  name: account-service
  credentials:
    username: test
    password: password123

registry:
  baseUrl: http://localhost:9020
  credentials:
    username: registry
    password: N4ch0s-A11-DAY!

server:
  applicationConnectors:
  - type: http
    port: 9030
  adminConnectors:
  - type: http
    port: 9031

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://192.168.33.55:5432/account-service-db
  user: account-service-db-user
  password: password123

httpClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true